<?php
/**
 * @file
 * Code for the GSB Feature Working Paper Display feature.
 */

include_once 'gsb_feature_working_paper_display.features.inc';

/**
 * Implements hook_field_views_data_alter().
 */
function gsb_feature_working_paper_display_field_views_data_alter(&$data, $field, $module) {
  if ($field['field_name'] == 'field_has_pdf') {
    foreach ($data as $table_name => $table_data) {
      if (isset($table_data[$field['field_name']]['field'])) {
        $data[$table_name][$field['field_name']]['field']['handler'] = 'gsb_feature_working_paper_display_handler_field_has_pdf';
      }
    }
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_working_paper_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {
  // Alter 'Working Paper Filters' content pane settings form.
  if ($form_state['pane']->subtype == 'working_paper_filters-working_paper_filters_pane' && $form_state['view']->name == 'working_paper_filters' && $form_state['view']->current_display == 'working_paper_filters_pane') {
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_person_fac_single_ref_target_id']['#description'] = 'Enter faculty node ID.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    $form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = -98;
    $form['context']['#access'] = FALSE;

    $conf = $form_state['conf'];
    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -100,
      '#default_value' => !empty($conf['title_link']) ? $conf['title_link'] : '',
    );
    $form['override_title']['#weight'] = -105;
    $form = gsb_misc_fixes_associative_insert($form, 'override_title', $item);

    $form['#validate'][] = 'gsb_feature_working_paper_display_form_validate';
    $form['#submit'][] = 'gsb_feature_working_paper_display_form_submit';
  }
}

function gsb_feature_working_paper_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function gsb_feature_working_paper_display_form_submit($form, &$form_state) {
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter Working Paper Filters content pane title to be linked to a custom URL.
 */
function gsb_feature_working_paper_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'working_paper_filters-working_paper_filters_pane') {
    if (!empty($pane->configuration['title_link'])) {
      $content->title = l($content->title, $pane->configuration['title_link']);
    }
  }
}
