<?php
/**
 * @file
 * gsb_feature_working_paper_display.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function gsb_feature_working_paper_display_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function gsb_feature_working_paper_display_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}
