<?php
/**
 * @file
 * Code for the GSB Feature Working Paper Display feature.
 */

include_once 'gsb_feature_working_paper_display.features.inc';

/**
 * Implements hook_field_views_data_alter().
 */
function gsb_feature_working_paper_display_field_views_data_alter(&$data, $field, $module) {
  if ($field['field_name'] == 'field_has_pdf') {
    foreach ($data as $table_name => $table_data) {
      if (isset($table_data[$field['field_name']]['field'])) {
        $data[$table_name][$field['field_name']]['field']['handler'] = 'gsb_feature_working_paper_display_handler_field_has_pdf';
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_working_paper_display_form_alter(&$form, &$form_state, $form_id) {
  // Alter 'Working Paper Filters' content pane settings form.
  if ($form_id == 'views_content_views_panes_content_type_edit_form' && $form_state['pane']->subtype == 'working_paper_filters-working_paper_filters_pane') {
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_person_fac_single_ref_target_id']['#description'] = 'Enter faculty node ID.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_working_paper_display_form_validate';
    $form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = -98;
    $form['context']['#access'] = FALSE;
  }
}

function gsb_feature_working_paper_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}
